### PR TITLE
Cljfmt Style Checking

### PR DESCRIPTION
**Pull request by JamesLaverack**
Use [cljfmt](https://github.com/weavejester/cljfmt) to check the formatting of all Clojure and Clojurescript files in the project.

The diff on this one is large because of changes to bring the existing code in line with the default style rules. In particular [single space indentation of arguments](https://github.com/bbatsov/clojure-style-guide#one-space-indent).

If you'd rather not have such a large diff, I can rework this to give cljfmt a specific exclusion for that rule to use the two spaces used currently in the code.

### CODE REVIEW

**Comment by SevereOverfl0w** [comment]
Alex Miller has recommended against 3rd party applications adding data to deps.edn, so I'm not sure it's a good idea to have `:dirs` in deps.edn.

**Comment by JamesLaverack** [comment]
What would be the best location?

Earlier on this branch I just used command line arguments, but that meant
that extra configuration was duplicated in the `bin/lint` and
`bin/lint-fix` scripts.

Alternatively, I could use a different config file for it alongside
`deps.edn`?

**Comment by JamesLaverack** [comment]
For now I've taken the latter option and moved that configuration into a separate `cljfmt.edn` file.

Happy to move this elsewhere too. (`.cljfmt.edn` maybe?)

**Comment by jonpither** [comment]
Closing for now - the code has moved substantially.

**Pull request closed without merging**
